from __future__ import annotations
import argparse, json, os, sys
from pathlib import Path
from typing import Any
import yaml
from .config import DEFAULT_TEMPLATE_PATH, OUTPUT_DIR, ROOT_DIR
from .evidence_harvester import harvest_all_tech_evidence, write_evidence_harvest
from .formula_rules import write_formula_catalog
from .high_quality_report import build_sections, build_score_report, build_tech_to_value_bridge, build_claims_and_evidences, write_outputs
from .chair_summary import build_tech_chair_summary
from .tech_full_report import build_tech_full_report
from .history_tech_features import build_and_save_history_tech_feature
try:
    from .investor_tech_view import apply_investor_tech_view_saved_files
except Exception:
    apply_investor_tech_view_saved_files = None
from .patent_harvester import harvest_patent_evidence, write_patent_outputs
from .utils import clean_text
from common.output_paths import agent_output_dir, agent_output_path, output_candidates, read_json_first, rel_project_path as common_rel_project_path, write_json
from common.data_paths import company_config_path, company_slug

import re
ROOT=ROOT_DIR


def _rel_project_path(value: Any) -> str:
    """Return a project-relative path string for repo portability."""
    if value is None:
        return ""
    raw = str(value).strip()
    if not raw:
        return ""
    raw = raw.replace("\\", "/")
    try:
        p = Path(raw)
        if p.is_absolute():
            return str(p.resolve().relative_to(ROOT)).replace("\\", "/")
    except Exception:
        pass
    m = re.search(r"(?:^|.*?)(data[\/].*)$", raw)
    if m:
        return m.group(1).replace("\\", "/")
    m = re.search(r"(?:^|.*?)(workspace[\/].*)$", raw)
    if m:
        return m.group(1).replace("\\", "/")
    m = re.search(r"(?:^|.*?)(src[\/].*)$", raw)
    if m:
        return m.group(1).replace("\\", "/")
    return raw.replace("\\", "/")


def _relativize_dict_paths(data: Any) -> Any:
    if isinstance(data, dict):
        return {k: _relativize_dict_paths(v) for k, v in data.items()}
    if isinstance(data, list):
        return [_relativize_dict_paths(v) for v in data]
    if isinstance(data, (str, Path)):
        s = str(data)
        if "data" in s or "workspace" in s or ":\\" in s or ":/" in s or s.startswith("/"):
            return _rel_project_path(s)
    return data



def _load_kipris_tech_ml_features(cdir: str, tech_output_dir: Path) -> dict[str, Any]:
    """Load KIPRIS Tech ML feature JSON generated by build_kipris_tech_ml_features.py.

    This does not fetch KIPRIS again.
    It only connects the already-created feature JSON into Tech Agent runtime outputs.
    """
    candidates = [
        tech_output_dir / f"{cdir}_kipris_tech_ml_features.json",
        tech_output_dir / "kipris_tech_ml_features.json",
    ]
    candidates.extend(sorted(tech_output_dir.glob("*kipris*tech_ml*features*.json")))

    for candidate in candidates:
        try:
            if candidate.exists() and candidate.is_file():
                payload = json.loads(candidate.read_text(encoding="utf-8"))
                if isinstance(payload, dict):
                    payload.setdefault("_source_file", _rel_project_path(candidate))
                    return payload
        except Exception as exc:
            print(f"[Tech Agent] KIPRIS Tech ML feature load skipped: {candidate} / {exc}")

    return {}


def _merge_kipris_tech_ml_into_bridge(
    bridge: dict[str, Any],
    kipris_features: dict[str, Any],
) -> dict[str, Any]:
    """Apply conservative KIPRIS/IP feature adjustment to Tech-to-Value Bridge."""
    if not isinstance(bridge, dict):
        bridge = {}

    if not kipris_features:
        return bridge

    scores = kipris_features.get("scores") or {}
    adjustment = kipris_features.get("tech_to_value_bridge_adjustment") or {}

    try:
        adj_points = float(adjustment.get("bridge_adjustment_points") or 0)
    except Exception:
        adj_points = 0.0

    base_score = bridge.get("score")
    try:
        base_score_f = float(base_score)
    except Exception:
        base_score_f = None

    if base_score_f is not None and adj_points:
        bridge["score_before_kipris_tech_ml_adjustment"] = base_score_f
        bridge["score"] = round(max(0.0, min(100.0, base_score_f + adj_points)), 2)

    bridge["kipris_tech_ml_features"] = kipris_features
    bridge["kipris_tech_ml_score"] = scores.get("kipris_tech_ml_score")
    bridge["legal_stability_score_estimated"] = scores.get("legal_stability_score_estimated")
    bridge["portfolio_momentum_score"] = scores.get("portfolio_momentum_score")
    bridge["ip_technology_fit_score"] = scores.get("ip_technology_fit_score")
    bridge["bridge_adjustment_points"] = adjustment.get("bridge_adjustment_points")
    bridge["bridge_signal"] = adjustment.get("bridge_signal")
    bridge["kipris_bridge_usage_rule"] = adjustment.get("usage_rule")
    bridge["kipris_bridge_applied"] = True

    return bridge


def _append_kipris_tech_ml_to_appendix(
    appendix_path: str | Path | None,
    kipris_features: dict[str, Any],
) -> None:
    """Append KIPRIS Tech ML feature summary to the full appendix markdown."""
    if not appendix_path or not kipris_features:
        return

    path = Path(str(appendix_path))
    if not path.exists():
        return

    scores = kipris_features.get("scores") or {}
    counts = kipris_features.get("core_counts") or {}
    rates = kipris_features.get("core_rates") or {}
    adjustment = kipris_features.get("tech_to_value_bridge_adjustment") or {}

    block = f"""

---

## KIPRIS Tech ML Feature 반영 요약

- kipris_tech_ml_score: {scores.get("kipris_tech_ml_score", "확인 제한")}
- legal_stability_score_estimated: {scores.get("legal_stability_score_estimated", "확인 제한")}
- portfolio_momentum_score: {scores.get("portfolio_momentum_score", "확인 제한")}
- ip_technology_fit_score: {scores.get("ip_technology_fit_score", "확인 제한")}
- bridge_adjustment_points: {adjustment.get("bridge_adjustment_points", "확인 제한")}
- bridge_signal: {adjustment.get("bridge_signal", "확인 제한")}

### 핵심 KIPRIS 정량 신호

- total_patents: {counts.get("total_patents", "확인 제한")}
- registered_patents_estimated: {counts.get("registered_patents_estimated", "확인 제한")}
- alive_patents_estimated: {counts.get("alive_patents_estimated", "확인 제한")}
- recent_5y_application_patents: {counts.get("recent_5y_application_patents", "확인 제한")}
- semiconductor_related_ipc_patents: {counts.get("semiconductor_related_ipc_patents", "확인 제한")}
- registration_rate_estimated: {rates.get("registration_rate_estimated", "확인 제한")}
- alive_rate_among_registered_estimated: {rates.get("alive_rate_among_registered_estimated", "확인 제한")}

주의: 이 값은 기술/IP 포트폴리오 품질 보조 신호이며, 고객 채택·양산·매출 전환·FCF 개선의 직접 근거로 보지는 않는다.
"""

    current = path.read_text(encoding="utf-8")
    if "## KIPRIS Tech ML Feature 반영 요약" not in current:
        path.write_text(current.rstrip() + block + "\n", encoding="utf-8")

def resolve_company_dir(company:str)->str:
    raw=str(company or "").strip().strip('"').strip("'")
    if not raw:
        raise ValueError("회사 입력값이 비어 있습니다.")
    p=Path(raw)
    if not p.is_absolute():
        p=ROOT/p
    if p.name.lower()=="company.yaml":
        return company_slug(p.parent.parent.name if p.parent.name == "common" else p.parent.name)
    if p.exists() and p.is_dir() and (p/"common"/"company.yaml").exists():
        return company_slug(p.name)
    return company_slug(raw)

def load_company(company_dir:str)->dict[str,Any]:
    p=company_config_path(company_dir)
    if not p.exists():
        raise FileNotFoundError(f"회사 설정 파일이 없습니다: {p}")
    d=yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    d.setdefault("slug", company_slug(company_dir))
    return d

def run(company_dir:str, company_name:str|None=None)->dict[str,Any]:
    cdir=resolve_company_dir(company_dir); company=load_company(cdir)
    if company_name: company["corp_name"]=company_name
    cname=clean_text(company.get("corp_name") or company.get("name") or cdir)
    print(f"[Tech Agent v12] 근거 수집 시작: {cname} ({cdir})")
    tech_output_dir = agent_output_dir(cdir, "tech")

    # Evaluation-only Tech history signal.  This is generated from src_eval data
    # with strict as_of_date cutoff and is written next to Tech Agent outputs so
    # the history/evaluation pipeline can read it without touching production src.
    tech_history_feature = {}
    try:
        tech_as_of = (
            os.environ.get("TECH_AS_OF_DATE")
            or os.environ.get("ALPHAPROVE_DATA_CUTOFF_DATE")
            or os.environ.get("EVAL_AS_OF_DATE")
        )
        if tech_as_of:
            history_target = {
                "company": cname,
                "company_name": cname,
                "company_dir": cdir,
                "slug": cdir,
                "ticker": str(company.get("ticker") or company.get("stock_code") or ""),
                "stock_code": str(company.get("stock_code") or company.get("ticker") or ""),
            }
            history_field = str(company.get("field") or company.get("sector_field") or os.environ.get("ALPHAPROVE_FIELD") or "반도체")
            tech_history_feature = build_and_save_history_tech_feature(
                ROOT,
                history_field,
                history_target,
                tech_as_of,
                frequency=os.environ.get("ALPHAPROVE_EVAL_FREQUENCY", "monthly"),
                output_dir=tech_output_dir,
            )
            print(f"[Tech Agent history] as_of={tech_as_of} signal={tech_history_feature.get('signal')} status={tech_history_feature.get('status')}")
    except Exception as exc:
        tech_history_feature = {"signal": 0.0, "status": f"TECH_HISTORY_FEATURE_ERROR:{type(exc).__name__}", "error": str(exc)}
        print(f"[Tech Agent history] feature build skipped: {exc}")
    formula_files=write_formula_catalog(cdir,DEFAULT_TEMPLATE_PATH,tech_output_dir)
    harvest=harvest_all_tech_evidence(company,cdir,template_path=DEFAULT_TEMPLATE_PATH)

    # KIPRIS/특허 원천 파일이 있으면 Tech Agent 실행 시 자동으로 정규화·정량화한다.
    # 원천 파일 위치: data/<분야>/<기업명>/tech/source/ 또는 기존 workspace/data/tech_sources/<company_dir>/ fallback
    # 원천 파일이 없어도 전체 실행은 중단하지 않고 품질 플래그만 남긴다.
    patent_harvest=harvest_patent_evidence(company,cdir)
    patent_files=write_patent_outputs(cdir,patent_harvest,tech_output_dir)

    # Already-generated KIPRIS Tech ML features are merged here.
    # This keeps KIPRIS feature generation separate from Tech Agent runtime.
    kipris_features = _load_kipris_tech_ml_features(cdir, tech_output_dir)
    if kipris_features:
        patent_harvest["kipris_tech_ml_features"] = kipris_features
        patent_harvest["kipris_tech_ml_score"] = (kipris_features.get("scores") or {}).get("kipris_tech_ml_score")
        patent_harvest["legal_stability_score_estimated"] = (kipris_features.get("scores") or {}).get("legal_stability_score_estimated")
        patent_harvest["bridge_adjustment_points"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_adjustment_points")
        patent_harvest["bridge_signal"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_signal")

        harvest["kipris_tech_ml_features"] = kipris_features
        harvest.setdefault("quality_flags", [])
        harvest["quality_flags"].append("KIPRIS Tech ML features merged into Tech Agent runtime outputs.")

    harvest["patent_harvest"]=patent_harvest
    harvest.setdefault("docs",[])
    harvest["docs"].extend(patent_harvest.get("docs") or [])
    harvest.setdefault("quality_flags",[])
    for flag in patent_harvest.get("quality_flags") or []:
        harvest["quality_flags"].append(f"특허/IP: {flag}")

    harvest_files=write_evidence_harvest(cdir,harvest,tech_output_dir)
    sections=build_sections(harvest, company)
    score_report=build_score_report(company,sections,harvest)
    bridge=build_tech_to_value_bridge(company,harvest,sections,score_report)
    bridge=_merge_kipris_tech_ml_into_bridge(bridge,kipris_features)
    claims,evidences=build_claims_and_evidences(company,sections,bridge,harvest)
    files=write_outputs(cdir,company,sections,score_report,bridge,harvest,claims,evidences,tech_output_dir)
    files.update({"formula_catalog_json":formula_files.get("json"),"formula_catalog_md":formula_files.get("md"),"evidence_harvest_json":harvest_files.get("json"),"evidence_harvest_md":harvest_files.get("md"),"patent_json":patent_files.get("json"),"patent_md":patent_files.get("md"),"patent_csv":patent_files.get("csv")})
    opinion = "매수" if score_report["total_score"]>=29 else "보유" if score_report["total_score"]>=18 else "매도"
    chair_summary = build_tech_chair_summary(
        company_dir=cdir,
        company_name=cname,
        opinion=opinion,
        sections=sections,
        score_report=score_report,
        bridge=bridge,
        patent_harvest=patent_harvest,
        output_files=files,
    )
    files.update(chair_summary.get("summary_files") or {})
 
    full_appendix = build_tech_full_report(
        company_dir=cdir,
        company_name=cname,
        opinion=opinion,
        score_report=score_report,
        bridge=bridge,
        patent_harvest=patent_harvest,
        chair_summary=chair_summary,
        output_files=files,
        save=True,
    )
    files.update({
        "tech_full_appendix_md": full_appendix.get("path"),
        "tech_full_appendix_json": full_appendix.get("meta_path"),
    })

    _append_kipris_tech_ml_to_appendix(full_appendix.get("path"), kipris_features)
    # Rewrite Tech Chair summary after the full appendix is created so Chair
    # can show a relative appendix link instead of a local absolute path.
    try:
        summary_path = agent_output_dir(cdir, "tech") / "tech_chair_summary.json"
        if summary_path.exists():
            summary_payload = json.loads(summary_path.read_text(encoding="utf-8"))
            summary_payload.setdefault("summary_files", {})["tech_full_appendix_md"] = _rel_project_path(full_appendix.get("path"))
            summary_payload.setdefault("summary_files", {})["tech_full_appendix_json"] = _rel_project_path(full_appendix.get("meta_path"))
            summary_payload["detail_files"] = _relativize_dict_paths(files)
            summary_path.write_text(json.dumps(summary_payload, ensure_ascii=False, indent=2), encoding="utf-8")
            chair_summary = summary_payload
    except Exception as exc:
        print(f"[Tech Agent] chair summary path normalization skipped: {exc}")

    # 개인투자자용 Tech 최종 점수판 생성 및 chair_summary.json/md 병합.
    # 실패해도 기존 Tech Agent 본문과 Chair compact summary는 유지한다.
    if apply_investor_tech_view_saved_files is not None:
        try:
            investor_result = apply_investor_tech_view_saved_files(
                company_dir=cdir,
                company_name=cname,
                summary_payload=chair_summary if isinstance(chair_summary, dict) else None,
            )
            if isinstance(investor_result, dict):
                if isinstance(investor_result.get("summary"), dict):
                    chair_summary = investor_result["summary"]
                for k, v in (investor_result.get("output_files") or {}).items():
                    files[k] = v
        except Exception as exc:
            print(f"[Tech Agent] investor scorecard merge skipped: {exc}")
            files["tech_investor_scorecard_warning"] = f"investor scorecard merge failed: {exc}"

    result={"agent":"tech","company":cname,"company_dir":cdir,"opinion":opinion,"tech_signal":tech_history_feature.get("signal",0.0),"history_tech_feature":tech_history_feature,"claims":claims,"evidences":evidences,"source_contexts":[{"title":d.get("title"),"url":d.get("url"),"path":d.get("path"),"snippet":clean_text(d.get("text"))[:350],"relevance_score":d.get("relevance_score")} for d in (harvest.get("docs") or [])[:12]],"limitations":["기술 점수만으로 매수/매도 결론을 만들지 않고 Tech-to-Value Bridge로 고객 채택·양산·매출 전환·FCF 연결성을 확인한다.","회사 식별어 없는 일반 테마 뉴스/저관련 URL은 제외한다.","수식 정리 시트는 정량 표현 표준화용이며 목표주가나 확정 신용등급을 직접 산출하지 않는다.","상세 Excel-frame/KIPRIS/IP/Tech ML 풀버전은 Tech Agent 부록에 보관하고 Chair에는 compact summary만 전달한다."],"tech_score":score_report["total_score"],"score_report":score_report,"tech_to_value_inputs":bridge,"tech_chair_summary":chair_summary,"formula_catalog_summary":{"json":formula_files.get("json"),"md":formula_files.get("md"),"rule_count":harvest.get("formula_rule_count")},"evidence_harvest_summary":{"document_count":harvest.get("document_count"),"accepted_url_count":harvest.get("accepted_url_count"),"rejected_url_count":harvest.get("rejected_url_count"),"quality_flags":harvest.get("quality_flags"),"patent_record_count":patent_harvest.get("normalized_record_count"),"patent_company_matched_count":patent_harvest.get("company_matched_record_count")},"output_files":_relativize_dict_paths(files),"categories":sections}

    if kipris_features:
        result["kipris_tech_ml_features"] = kipris_features
        result["kipris_tech_ml_score"] = (kipris_features.get("scores") or {}).get("kipris_tech_ml_score")
        result["legal_stability_score_estimated"] = (kipris_features.get("scores") or {}).get("legal_stability_score_estimated")
        result["bridge_adjustment_points"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_adjustment_points")
        result["bridge_signal"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_signal")

        if isinstance(result.get("tech_chair_summary"), dict):
            result["tech_chair_summary"]["kipris_tech_ml_features"] = kipris_features
            result["tech_chair_summary"]["kipris_tech_ml_score"] = result["kipris_tech_ml_score"]
            result["tech_chair_summary"]["legal_stability_score_estimated"] = result["legal_stability_score_estimated"]
            result["tech_chair_summary"]["bridge_adjustment_points"] = result["bridge_adjustment_points"]
            result["tech_chair_summary"]["bridge_signal"] = result["bridge_signal"]

    # Canonical JSON outputs for the current data/<field>/<company>/<agent>/ structure.
    # Chair and Auditor can read either <slug>_tech.json or <slug>_tech_agent_packet.json.
    try:
        tech_json_path = agent_output_path(cdir, "tech", f"{cdir}_tech.json")
        tech_packet_path = agent_output_path(cdir, "tech", f"{cdir}_tech_agent_packet.json")
        result.setdefault("output_files", {}).update({
            "tech_history_feature_json": _rel_project_path(tech_history_feature.get("history_feature_json", "")),
            "tech_history_feature_csv": _rel_project_path(tech_history_feature.get("history_feature_csv", "")),
            "tech_json": _rel_project_path(tech_json_path),
            "tech_agent_packet_json": _rel_project_path(tech_packet_path),
        })
        write_json(tech_json_path, result)
        write_json(tech_packet_path, result)
    except Exception as exc:
        print(f"[Tech Agent] canonical JSON 저장 실패: {exc}")

    print(f"[Tech Agent v13] 완료: score={score_report['total_score']}/35, bridge={bridge['score']}/100, grade={bridge['grade']}, patents={patent_harvest.get('normalized_record_count',0)}건")
    print(f"[Tech Agent v13] Chair compact summary: {files.get('chair_summary_md')}")
    print(f"[Tech Agent v13] Tech full appendix: {files.get('tech_full_appendix_md')}")
    for k,v in files.items(): print(f"  - {k}: {_rel_project_path(v)}")
    return result

def run_tech_agent(company_dir:str, company:str|None=None)->dict[str,Any]: return run(company_dir,company)
def run_tech(company_dir:str, company:str|None=None)->dict[str,Any]: return run(company_dir,company)

def main(argv:list[str]|None=None)->int:
    parser=argparse.ArgumentParser(description="Tech Agent v12 - excel-frame + KIPRIS/IP quantification + Chair tech section")
    parser.add_argument("--company",type=str,required=False)
    parser.add_argument("--company-dir",type=str,required=False)
    parser.add_argument("--company-name","--name",dest="company_name",type=str,required=False)
    parser.add_argument("--json",action="store_true")
    args=parser.parse_args(argv)
    target=args.company_dir or args.company
    if not target: parser.error("--company 또는 --company-dir 중 하나는 필요합니다.")
    res=run_tech_agent(target,args.company_name)
    if args.json: print(json.dumps(res,ensure_ascii=False,indent=2))
    return 0
if __name__=="__main__": raise SystemExit(main())
