from __future__ import annotations
import argparse, csv, json, re
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DEFAULT_CSV = DATA / "반도체" / "_sector_common" / "universe" / "universe_30_semiconductor_20260514.csv"
AGENTS = ["intake","finance","market","issue","macro","tech","valuation","auditor","chair"]
ORIGINAL_5 = {"nepes","hanmi","hansol","duksan","ltc"}

def safe_name(value: Any, default: str = "unknown") -> str:
    text = str(value or "").strip().strip('"').strip("'")
    text = re.sub(r"[\\/:*?\"<>|]+", "_", text)
    text = re.sub(r"\s+", "_", text).strip("._ ")
    return text or default

def truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in {"1","true","y","yes","include"}

def q(value: Any) -> str:
    return '"' + str(value or "").replace('"','\\"') + '"'

def yf_ticker(code: str, market: str) -> str:
    code = str(code or "").zfill(6)
    m = str(market or "").upper().strip()
    return f"{code}.KS" if m == "KOSPI" else f"{code}.KQ" if m == "KOSDAQ" else code

def read_rows(path: Path) -> list[dict[str,str]]:
    if not path.exists():
        raise FileNotFoundError(f"Universe CSV not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = [dict(r) for r in csv.DictReader(f)]
    rows = [r for r in rows if truthy(r.get("include_in_evaluation","1"))]
    if not rows:
        raise ValueError(f"No included rows: {path}")
    return rows

def write_company_yaml(row: dict[str,str], dry_run: bool = False) -> dict[str, Any]:
    company = str(row.get("company_name") or "").strip()
    slug = safe_name(row.get("company_dir"), company)
    field = str(row.get("field") or "반도체").strip() or "반도체"
    sector = str(row.get("sector") or field).strip() or field
    peer_group = str(row.get("peer_group") or "").strip()
    code = str(row.get("stock_code") or "").strip().zfill(6)
    market = str(row.get("market") or "").strip().upper()
    ticker = yf_ticker(code, market)
    company_root = DATA / field / company
    common_dir = company_root / "_company_common"
    yaml_path = common_dir / "company.yaml"
    if not dry_run:
        common_dir.mkdir(parents=True, exist_ok=True)
        for agent in AGENTS:
            (company_root / agent).mkdir(parents=True, exist_ok=True)
        lines = [
            "# Auto-generated by scripts/bootstrap_chair_25_universe.py",
            "# Keep this fixed once evaluation starts.",
            f"slug: {q(slug)}",
            f"company_dir: {q(slug)}",
            f"corp_name: {q(company)}",
            f"display_name: {q(company)}",
            f"output_name: {q(company)}",
            f"field: {q(field)}",
            f"industry_field: {q(field)}",
            f"sector: {q(sector)}",
            f"peer_group: {q(peer_group)}",
            f"stock_code: {q(code)}",
            f"ticker: {q(ticker)}",
            f"market: {q(market)}",
            "include_in_evaluation: true",
            f"universe_name: {q('universe_30_semiconductor_20260514')}",
            f"locked_as_of: {q('2026-05-14')}",
            f"finance_file: {q(company + '_재무.csv')}",
            f"stock_file: {q(company + '_주식.csv')}",
            "aliases:",
            f"  - {q(company)}",
            f"  - {q(slug)}",
            f"  - {q(code)}",
            f"  - {q(ticker)}",
            "",
        ]
        yaml_path.write_text("\n".join(lines), encoding="utf-8")
    return {"company_name":company,"company_dir":slug,"stock_code":code,"ticker":ticker,"yaml_path":str(yaml_path),"dry_run":dry_run}

def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--csv", default=str(DEFAULT_CSV))
    p.add_argument("--only-new-25", action="store_true")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    rows = read_rows(Path(args.csv))
    if args.only_new_25:
        rows = [r for r in rows if safe_name(r.get("company_dir")) not in ORIGINAL_5]
    out = [write_company_yaml(r, dry_run=args.dry_run) for r in rows]
    print(json.dumps({"status":"DRY_RUN" if args.dry_run else "OK","created_at":datetime.now().isoformat(timespec="seconds"),"count":len(out),"companies":out}, ensure_ascii=False, indent=2))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
