from __future__ import annotations

import argparse
import csv
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

AGENTS = [
    "intake",
    "finance",
    "market",
    "issue",
    "macro",
    "tech",
    "valuation",
    "auditor",
    "chair",
]

DEFAULT_CSV = (
    DATA
    / "반도체"
    / "_sector_common"
    / "universe"
    / "universe_30_semiconductor_20260514.csv"
)


def safe_name(value: Any, default: str = "unknown") -> str:
    text = str(value or "").strip().strip('"').strip("'")
    text = re.sub(r"[\\/:*?\"<>|]+", "_", text)
    text = re.sub(r"\s+", "_", text).strip("._ ")
    return text or default


def truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "y", "yes", "include"}


def yaml_scalar(value: Any) -> str:
    # Always quote for Korean/leading-zero stock codes/strings with slash.
    s = str(value or "").replace('"', '\\"')
    return f'"{s}"'


def read_universe(csv_path: Path) -> list[dict[str, str]]:
    if not csv_path.exists():
        raise FileNotFoundError(f"Universe CSV not found: {csv_path}")
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = [dict(row) for row in csv.DictReader(f)]
    rows = [r for r in rows if truthy(r.get("include_in_evaluation", "1"))]
    if not rows:
        raise ValueError(f"No included companies in {csv_path}")
    return rows


def validate_rows(rows: list[dict[str, str]]) -> None:
    seen_slugs: set[str] = set()
    seen_codes: set[str] = set()
    seen_names: set[str] = set()
    errors: list[str] = []

    required = ["company_name", "company_dir", "stock_code", "market", "field", "peer_group"]
    for i, row in enumerate(rows, start=1):
        for key in required:
            if not str(row.get(key, "")).strip():
                errors.append(f"row {i}: missing {key}")
        slug = safe_name(row.get("company_dir"), "")
        code = str(row.get("stock_code") or "").zfill(6)
        name = str(row.get("company_name") or "").strip()
        if slug in seen_slugs:
            errors.append(f"duplicate company_dir: {slug}")
        if code in seen_codes:
            errors.append(f"duplicate stock_code: {code}")
        if name in seen_names:
            errors.append(f"duplicate company_name: {name}")
        seen_slugs.add(slug)
        seen_codes.add(code)
        seen_names.add(name)

    if errors:
        raise ValueError("Universe CSV validation failed:\n- " + "\n- ".join(errors))


def ensure_sector_tree(field: str, dry_run: bool = False) -> list[Path]:
    paths = [
        DATA / "_global_common",
        DATA / "_global_common" / "macro",
        DATA / field,
        DATA / field / "_sector_common",
        DATA / field / "_sector_common" / "data",
        DATA / field / "_sector_common" / "source_data",
        DATA / field / "_sector_common" / "templates",
        DATA / field / "_sector_common" / "ml_universe",
        DATA / field / "_sector_common" / "universe",
        DATA / field / "_sector_common" / "evaluation",
    ]
    if not dry_run:
        for p in paths:
            p.mkdir(parents=True, exist_ok=True)
    return paths


def build_company_yaml(row: dict[str, str]) -> str:
    name = str(row.get("company_name") or "").strip()
    slug = safe_name(row.get("company_dir"), name)
    stock_code = str(row.get("stock_code") or "").strip().zfill(6)
    market = str(row.get("market") or "").strip()
    field = str(row.get("field") or "반도체").strip()
    peer_group = str(row.get("peer_group") or "").strip()
    ticker = str(row.get("ticker") or "").strip()

    aliases = [name, slug, stock_code, ticker]
    aliases_block = "\n".join(f"  - {yaml_scalar(x)}" for x in aliases if x)

    data = {
        "slug": slug,
        "company_dir": slug,
        "corp_name": name,
        "display_name": name,
        "output_name": name,
        "field": field,
        "industry_field": field,
        "sector": str(row.get("sector") or field).strip(),
        "peer_group": peer_group,
        "stock_code": stock_code,
        "ticker": ticker,
        "market": market,
        "include_in_evaluation": "true",
        "universe_name": "universe_30_semiconductor_20260514",
        "universe_source": str(row.get("universe_source") or "").strip(),
        "selection_bucket": str(row.get("selection_bucket") or "").strip(),
        "selection_reason": str(row.get("selection_reason") or "").strip(),
        "locked_as_of": str(row.get("locked_as_of") or "2026-05-14").strip(),
        "finance_file": f"{name}_재무.csv",
        "stock_file": f"{name}_주식.csv",
    }

    lines: list[str] = []
    lines.append("# Auto-generated by scripts/bootstrap_semiconductor_universe_30.py")
    lines.append("# Do not change after evaluation start unless the universe lock is intentionally revised.")
    for key, value in data.items():
        if key == "include_in_evaluation":
            lines.append(f"{key}: true")
        else:
            lines.append(f"{key}: {yaml_scalar(value)}")
    lines.append("aliases:")
    lines.append(aliases_block or f"  - {yaml_scalar(name)}")
    lines.append("")
    return "\n".join(lines)


def create_company_tree(row: dict[str, str], *, overwrite_yaml: bool = False, dry_run: bool = False) -> list[Path]:
    field = str(row.get("field") or "반도체").strip()
    company_name = str(row.get("company_name") or "").strip()
    company_root = DATA / field / company_name
    paths = [company_root, company_root / "_company_common"]
    for agent in AGENTS:
        paths.append(company_root / agent)
    paths.append(company_root / "tech" / "source")

    if not dry_run:
        for p in paths:
            p.mkdir(parents=True, exist_ok=True)
        yaml_path = company_root / "_company_common" / "company.yaml"
        if overwrite_yaml or not yaml_path.exists():
            yaml_path.write_text(build_company_yaml(row), encoding="utf-8")
    return paths


def write_lock_files(csv_path: Path, rows: list[dict[str, str]], field: str, *, dry_run: bool = False) -> tuple[Path, Path]:
    universe_dir = DATA / field / "_sector_common" / "universe"
    lock_json = universe_dir / "universe_30_semiconductor_20260514.lock.json"
    targets_txt = universe_dir / "run_targets_30.txt"

    payload = {
        "universe_name": "universe_30_semiconductor_20260514",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "csv_path": str(csv_path.relative_to(ROOT)).replace("\\", "/") if csv_path.is_absolute() else str(csv_path),
        "selection_policy": {
            "universe_source": "Tech/Valuation peer universe + 반도체 밸류체인 대표성 B안",
            "filters": [
                "상장 유지 후보",
                "가격 데이터 존재 후보",
                "재무/공시 데이터 존재 후보",
                "거래정지/관리종목/심각한 결측 제외 후보",
            ],
            "selection_basis": [
                "기존 5개 기준기업 유지",
                "반도체 밸류체인 대표성",
                "Tech/Valuation 확장 실행 가능성",
                "평가 시작 전 사전 고정",
            ],
            "post_return_editing_allowed": False,
        },
        "company_count": len(rows),
        "companies": [
            {
                "rank": r.get("rank"),
                "company_name": r.get("company_name"),
                "company_dir": r.get("company_dir"),
                "stock_code": str(r.get("stock_code") or "").zfill(6),
                "market": r.get("market"),
                "peer_group": r.get("peer_group"),
                "is_original_5": r.get("is_original_5"),
            }
            for r in rows
        ],
    }

    targets = []
    for r in rows:
        name = r.get("company_name", "")
        slug = safe_name(r.get("company_dir"), name)
        targets.append(f'{slug}\t{name}\t{str(r.get("stock_code") or "").zfill(6)}\t{r.get("market", "")}')

    if not dry_run:
        universe_dir.mkdir(parents=True, exist_ok=True)
        lock_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        targets_txt.write_text("company_dir\tcompany_name\tstock_code\tmarket\n" + "\n".join(targets) + "\n", encoding="utf-8")
    return lock_json, targets_txt


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap AlphaProve 30-company semiconductor universe")
    parser.add_argument("--csv", default=str(DEFAULT_CSV), help="Universe CSV path")
    parser.add_argument("--field", default="반도체", help="Field name, default: 반도체")
    parser.add_argument("--overwrite-yaml", action="store_true", help="Overwrite existing company.yaml files")
    parser.add_argument("--dry-run", action="store_true", help="Validate and print actions without writing files")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.is_absolute():
        csv_path = ROOT / csv_path

    rows = read_universe(csv_path)
    validate_rows(rows)

    print(f"[Universe] CSV: {csv_path}")
    print(f"[Universe] included companies: {len(rows)}")
    print(f"[Universe] field: {args.field}")
    print(f"[Universe] dry_run: {args.dry_run}")

    ensure_sector_tree(args.field, dry_run=args.dry_run)
    for row in rows:
        create_company_tree(row, overwrite_yaml=args.overwrite_yaml, dry_run=args.dry_run)
        print(f"  - {row.get('company_dir')} / {row.get('company_name')} / {row.get('stock_code')}")

    lock_json, targets_txt = write_lock_files(csv_path, rows, args.field, dry_run=args.dry_run)
    print("[DONE] Universe tree bootstrapped")
    print(f"[LOCK] {lock_json}")
    print(f"[TARGETS] {targets_txt}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
