from __future__ import annotations

import argparse
import csv
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

DEFAULT_CSV = DATA / "반도체" / "_sector_common" / "universe" / "universe_30_semiconductor_20260514.csv"
AGENTS = ["intake", "finance", "market", "issue", "macro", "tech", "valuation", "auditor", "chair"]
ORIGINAL_5 = {"nepes", "hanmi", "hansol", "duksan", "ltc"}


def safe_name(value: Any, default: str = "unknown") -> str:
    text = str(value or "").strip().strip('"').strip("'")
    text = re.sub(r"[\\/:*?\"<>|]+", "_", text)
    text = re.sub(r"\s+", "_", text).strip("._ ")
    return text or default


def truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "y", "yes", "include"}


def q(value: Any) -> str:
    return '"' + str(value or "").replace('"', '\\"') + '"'


def yf_ticker(code: str, market: str) -> str:
    code = str(code or "").zfill(6)
    m = str(market or "").upper().strip()
    if m == "KOSPI":
        return f"{code}.KS"
    if m == "KOSDAQ":
        return f"{code}.KQ"
    return code


def tech_keywords(peer_group: str) -> list[str]:
    text = str(peer_group or "")
    base = ["반도체", "공정", "양산", "고객", "R&D", "특허", "기술경쟁력"]
    mapping = {
        "후공정": ["후공정", "패키징", "테스트", "WLP", "Bumping", "수율"],
        "패키징": ["후공정", "패키징", "테스트", "WLP", "Bumping", "수율"],
        "테스트": ["테스트", "검사", "소켓", "신뢰성", "수율"],
        "소켓": ["테스트", "소켓", "인터페이스", "신뢰성"],
        "소재": ["반도체 소재", "전구체", "고순도", "식각", "세정", "증착"],
        "부품": ["부품", "소모품", "공정 안정성", "수명"],
        "장비": ["반도체 장비", "공정장비", "검사장비", "자동화", "CAPEX"],
        "검사": ["검사장비", "계측", "수율", "품질관리"],
        "팹리스": ["팹리스", "설계", "시스템반도체", "MCU", "SoC"],
        "설계": ["팹리스", "설계", "시스템반도체", "SoC"],
        "디자인": ["디자인하우스", "디자인솔루션", "파운드리 연계", "설계"],
        "파운드리": ["파운드리", "웨이퍼", "공정기술", "수율"],
        "차량용": ["차량용 반도체", "전장", "MCU", "신뢰성"],
        "메모리": ["메모리", "반도체 설계", "스토리지"],
    }
    out = list(base)
    for key, vals in mapping.items():
        if key in text:
            out.extend(vals)
    seen = []
    for x in out:
        if x not in seen:
            seen.append(x)
    return seen


def read_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Universe CSV not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = [dict(r) for r in csv.DictReader(f)]
    rows = [r for r in rows if truthy(r.get("include_in_evaluation", "1"))]
    if not rows:
        raise ValueError(f"No included rows: {path}")
    return rows


def write_company_yaml(row: dict[str, str], *, dry_run: bool = False) -> dict[str, Any]:
    company = str(row.get("company_name") or "").strip()
    slug = safe_name(row.get("company_dir"), company)
    field = str(row.get("field") or "반도체").strip() or "반도체"
    sector = str(row.get("sector") or field).strip() or field
    peer_group = str(row.get("peer_group") or "").strip()
    code = str(row.get("stock_code") or "").strip().zfill(6)
    market = str(row.get("market") or "").strip().upper()
    ticker = yf_ticker(code, market)
    keywords = tech_keywords(peer_group)

    company_root = DATA / field / company
    common_dir = company_root / "_company_common"
    yaml_path = common_dir / "company.yaml"

    for agent in AGENTS:
        path = company_root / agent
        if not dry_run:
            path.mkdir(parents=True, exist_ok=True)
    if not dry_run:
        common_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Auto-generated by scripts/bootstrap_tech_25_universe.py",
        "# Keep this fixed once evaluation starts.",
        f"slug: {q(slug)}",
        f"company_dir: {q(slug)}",
        f"corp_name: {q(company)}",
        f"display_name: {q(company)}",
        f"output_name: {q(company)}",
        f"field: {q(field)}",
        f"industry_field: {q(field)}",
        f"sector: {q(sector)}",
        f"peer_group: {q(peer_group)}",
        f"stock_code: {q(code)}",
        f"ticker: {q(ticker)}",
        f"market: {q(market)}",
        "include_in_evaluation: true",
        f"universe_name: {q('universe_30_semiconductor_20260514')}",
        f"locked_as_of: {q('2026-05-14')}",
        f"finance_file: {q(company + '_재무.csv')}",
        f"stock_file: {q(company + '_주식.csv')}",
        "tech_data_status: \"BOOTSTRAP_FROM_LOCKED_UNIVERSE\"",
        "tech_keywords:",
        *[f"  - {q(x)}" for x in keywords],
        "core_keywords:",
        *[f"  - {q(x)}" for x in keywords[:10]],
        "products:",
        *[f"  - {q(x)}" for x in keywords if x not in {"반도체", "공정", "양산", "고객", "R&D", "특허", "기술경쟁력"}],
        "aliases:",
        f"  - {q(company)}",
        f"  - {q(slug)}",
        f"  - {q(code)}",
        f"  - {q(ticker)}",
        "",
    ]

    if not dry_run:
        yaml_path.write_text("\n".join(lines), encoding="utf-8")

    return {
        "company_name": company,
        "company_dir": slug,
        "stock_code": code,
        "ticker": ticker,
        "peer_group": peer_group,
        "yaml_path": str(yaml_path),
        "dry_run": dry_run,
    }


def main() -> int:
    p = argparse.ArgumentParser(description="Bootstrap AlphaProve semiconductor universe metadata for tech automation.")
    p.add_argument("--csv", default=str(DEFAULT_CSV))
    p.add_argument("--only-new-25", action="store_true", help="exclude original 5 companies")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    rows = read_rows(Path(args.csv))
    if args.only_new_25:
        rows = [r for r in rows if safe_name(r.get("company_dir")) not in ORIGINAL_5]

    out = [write_company_yaml(r, dry_run=args.dry_run) for r in rows]
    print(json.dumps({
        "status": "DRY_RUN" if args.dry_run else "OK",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "count": len(out),
        "companies": out,
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
