from pathlib import Path

path = Path("src/tech_agent/runner.py")
text = path.read_text(encoding="utf-8")

if "_load_kipris_tech_ml_features" not in text:
    helper = r'''

def _load_kipris_tech_ml_features(cdir: str, tech_output_dir: Path) -> dict[str, Any]:
    """Load KIPRIS Tech ML feature JSON generated by build_kipris_tech_ml_features.py.

    This does not fetch KIPRIS again.
    It only connects the already-created feature JSON into Tech Agent runtime outputs.
    """
    candidates = [
        tech_output_dir / f"{cdir}_kipris_tech_ml_features.json",
        tech_output_dir / "kipris_tech_ml_features.json",
    ]
    candidates.extend(sorted(tech_output_dir.glob("*kipris*tech_ml*features*.json")))

    for candidate in candidates:
        try:
            if candidate.exists() and candidate.is_file():
                payload = json.loads(candidate.read_text(encoding="utf-8"))
                if isinstance(payload, dict):
                    payload.setdefault("_source_file", _rel_project_path(candidate))
                    return payload
        except Exception as exc:
            print(f"[Tech Agent] KIPRIS Tech ML feature load skipped: {candidate} / {exc}")

    return {}


def _merge_kipris_tech_ml_into_bridge(
    bridge: dict[str, Any],
    kipris_features: dict[str, Any],
) -> dict[str, Any]:
    """Apply conservative KIPRIS/IP feature adjustment to Tech-to-Value Bridge."""
    if not isinstance(bridge, dict):
        bridge = {}

    if not kipris_features:
        return bridge

    scores = kipris_features.get("scores") or {}
    adjustment = kipris_features.get("tech_to_value_bridge_adjustment") or {}

    try:
        adj_points = float(adjustment.get("bridge_adjustment_points") or 0)
    except Exception:
        adj_points = 0.0

    base_score = bridge.get("score")
    try:
        base_score_f = float(base_score)
    except Exception:
        base_score_f = None

    if base_score_f is not None and adj_points:
        bridge["score_before_kipris_tech_ml_adjustment"] = base_score_f
        bridge["score"] = round(max(0.0, min(100.0, base_score_f + adj_points)), 2)

    bridge["kipris_tech_ml_features"] = kipris_features
    bridge["kipris_tech_ml_score"] = scores.get("kipris_tech_ml_score")
    bridge["legal_stability_score_estimated"] = scores.get("legal_stability_score_estimated")
    bridge["portfolio_momentum_score"] = scores.get("portfolio_momentum_score")
    bridge["ip_technology_fit_score"] = scores.get("ip_technology_fit_score")
    bridge["bridge_adjustment_points"] = adjustment.get("bridge_adjustment_points")
    bridge["bridge_signal"] = adjustment.get("bridge_signal")
    bridge["kipris_bridge_usage_rule"] = adjustment.get("usage_rule")
    bridge["kipris_bridge_applied"] = True

    return bridge


def _append_kipris_tech_ml_to_appendix(
    appendix_path: str | Path | None,
    kipris_features: dict[str, Any],
) -> None:
    """Append KIPRIS Tech ML feature summary to the full appendix markdown."""
    if not appendix_path or not kipris_features:
        return

    path = Path(str(appendix_path))
    if not path.exists():
        return

    scores = kipris_features.get("scores") or {}
    counts = kipris_features.get("core_counts") or {}
    rates = kipris_features.get("core_rates") or {}
    adjustment = kipris_features.get("tech_to_value_bridge_adjustment") or {}

    block = f"""

---

## KIPRIS Tech ML Feature 반영 요약

- kipris_tech_ml_score: {scores.get("kipris_tech_ml_score", "확인 제한")}
- legal_stability_score_estimated: {scores.get("legal_stability_score_estimated", "확인 제한")}
- portfolio_momentum_score: {scores.get("portfolio_momentum_score", "확인 제한")}
- ip_technology_fit_score: {scores.get("ip_technology_fit_score", "확인 제한")}
- bridge_adjustment_points: {adjustment.get("bridge_adjustment_points", "확인 제한")}
- bridge_signal: {adjustment.get("bridge_signal", "확인 제한")}

### 핵심 KIPRIS 정량 신호

- total_patents: {counts.get("total_patents", "확인 제한")}
- registered_patents_estimated: {counts.get("registered_patents_estimated", "확인 제한")}
- alive_patents_estimated: {counts.get("alive_patents_estimated", "확인 제한")}
- recent_5y_application_patents: {counts.get("recent_5y_application_patents", "확인 제한")}
- semiconductor_related_ipc_patents: {counts.get("semiconductor_related_ipc_patents", "확인 제한")}
- registration_rate_estimated: {rates.get("registration_rate_estimated", "확인 제한")}
- alive_rate_among_registered_estimated: {rates.get("alive_rate_among_registered_estimated", "확인 제한")}

주의: 이 값은 기술/IP 포트폴리오 품질 보조 신호이며, 고객 채택·양산·매출 전환·FCF 개선의 직접 근거로 보지는 않는다.
"""

    current = path.read_text(encoding="utf-8")
    if "## KIPRIS Tech ML Feature 반영 요약" not in current:
        path.write_text(current.rstrip() + block + "\n", encoding="utf-8")
'''

    marker = "\ndef resolve_company_dir"
    text = text.replace(marker, helper + marker)

old = '''    patent_harvest=harvest_patent_evidence(company,cdir)
    patent_files=write_patent_outputs(cdir,patent_harvest,tech_output_dir)
    harvest["patent_harvest"]=patent_harvest
'''

new = '''    patent_harvest=harvest_patent_evidence(company,cdir)
    patent_files=write_patent_outputs(cdir,patent_harvest,tech_output_dir)

    # Already-generated KIPRIS Tech ML features are merged here.
    # This keeps KIPRIS feature generation separate from Tech Agent runtime.
    kipris_features = _load_kipris_tech_ml_features(cdir, tech_output_dir)
    if kipris_features:
        patent_harvest["kipris_tech_ml_features"] = kipris_features
        patent_harvest["kipris_tech_ml_score"] = (kipris_features.get("scores") or {}).get("kipris_tech_ml_score")
        patent_harvest["legal_stability_score_estimated"] = (kipris_features.get("scores") or {}).get("legal_stability_score_estimated")
        patent_harvest["bridge_adjustment_points"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_adjustment_points")
        patent_harvest["bridge_signal"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_signal")

        harvest["kipris_tech_ml_features"] = kipris_features
        harvest.setdefault("quality_flags", [])
        harvest["quality_flags"].append("KIPRIS Tech ML features merged into Tech Agent runtime outputs.")

    harvest["patent_harvest"]=patent_harvest
'''

if old in text and "kipris_features = _load_kipris_tech_ml_features" not in text:
    text = text.replace(old, new)
elif old not in text:
    print("[WARN] patent_harvest insertion point not found. runner.py may already differ.")

old = '''    bridge=build_tech_to_value_bridge(company,harvest,sections,score_report)
'''
new = '''    bridge=build_tech_to_value_bridge(company,harvest,sections,score_report)
    bridge=_merge_kipris_tech_ml_into_bridge(bridge,kipris_features)
'''

if old in text and "bridge=_merge_kipris_tech_ml_into_bridge" not in text:
    text = text.replace(old, new)
elif old not in text:
    print("[WARN] bridge insertion point not found. runner.py may already differ.")

old = '''    files.update({
        "tech_full_appendix_md": full_appendix.get("path"),
        "tech_full_appendix_json": full_appendix.get("meta_path"),
    })
'''

new = '''    files.update({
        "tech_full_appendix_md": full_appendix.get("path"),
        "tech_full_appendix_json": full_appendix.get("meta_path"),
    })

    _append_kipris_tech_ml_to_appendix(full_appendix.get("path"), kipris_features)
'''

if old in text and "_append_kipris_tech_ml_to_appendix(full_appendix.get(\"path\"), kipris_features)" not in text:
    text = text.replace(old, new)
elif old not in text:
    print("[WARN] full appendix insertion point not found. runner.py may already differ.")

old = '''    # Canonical JSON outputs for the current data/<field>/<company>/<agent>/ structure.
'''

new = '''    if kipris_features:
        result["kipris_tech_ml_features"] = kipris_features
        result["kipris_tech_ml_score"] = (kipris_features.get("scores") or {}).get("kipris_tech_ml_score")
        result["legal_stability_score_estimated"] = (kipris_features.get("scores") or {}).get("legal_stability_score_estimated")
        result["bridge_adjustment_points"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_adjustment_points")
        result["bridge_signal"] = (kipris_features.get("tech_to_value_bridge_adjustment") or {}).get("bridge_signal")

        if isinstance(result.get("tech_chair_summary"), dict):
            result["tech_chair_summary"]["kipris_tech_ml_features"] = kipris_features
            result["tech_chair_summary"]["kipris_tech_ml_score"] = result["kipris_tech_ml_score"]
            result["tech_chair_summary"]["legal_stability_score_estimated"] = result["legal_stability_score_estimated"]
            result["tech_chair_summary"]["bridge_adjustment_points"] = result["bridge_adjustment_points"]
            result["tech_chair_summary"]["bridge_signal"] = result["bridge_signal"]

    # Canonical JSON outputs for the current data/<field>/<company>/<agent>/ structure.
'''

if old in text and 'result["kipris_tech_ml_features"] = kipris_features' not in text:
    text = text.replace(old, new)
elif old not in text:
    print("[WARN] result insertion point not found. runner.py may already differ.")

path.write_text(text, encoding="utf-8")
print("[DONE] patched src/tech_agent/runner.py")
